theme: jekyll-theme-slate
title: "Fast, High-Quality and Parameter-Efficient Articulatory Synthesis Using Differentiable DSP"
author : "Yisi Liu, Bohan Yu, Drake Lin, Peter Wu, Cheol Jun Cho, Gopala Krishna Anumanchipalli"

