device : 'cuda:0'
 
# model hyperparameters
hidden_dim : 256
nharmonics : 50
nbands : 65
fs : 16000
framesize : 80
attenuate : 0.01
reverb_len : 1025
dilations : [1, 2, 4, 8, 16]
nstacks : 4

# discriminator 
features : [32, 64, 128, 256]
scales : [2048, 1024, 512, 256, 128, 64]

# training parameters
fft_factor : 1
overlap : 0.75

lr_gen : 3.0e-4
lr_disc : 3.0e-6
alpha : 1.0
beta : 5.0
milestones : [2400, 4800]
gamma : 0.3
total_epochs : 6400
comment : 'SLT2024'
batch_size : 32

# folder names
wav_dir: _
ema_dir: _
pitch_dir : _
loudness_dir : _
data_split_dir: _
